//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml;
using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class config
{

	private configSip[] sipField;

	private configGsm[] gsmField;

	private configGate[] gateField;

	private string versionField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("sip", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public configSip[] sip
	{
		get
		{
			return this.sipField;
		}
		set
		{
			this.sipField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("gsm", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public configGsm[] gsm
	{
		get
		{
			return this.gsmField;
		}
		set
		{
			this.gsmField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("gate", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public configGate[] gate
	{
		get
		{
			return this.gateField;
		}
		set
		{
			this.gateField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string version
	{
		get
		{
			return this.versionField;
		}
		set
		{
			this.versionField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class configSip
{

	private string registrationField;

	private int registration_intervalField;

	private string domainField;

	private int domain_portField;

	private string proxyField;

	private int proxy_portField;

	private int local_portField;

	private string user_nameField;

	private string loginField;

	private string passwordField;

	private string keepaliveField;

	private string keepalive_intervalField;

	private string dtmf_typeField;

	private string codec1Field;

	private string codec2Field;

	private string codec3Field;

	private string codec4Field;

	private string cid_whereField;

	private string rejection_codeField;

	/// <remarks/>
	[XmlIgnore]
	public string registration
	{
		get
		{
			return this.registrationField;
		}
		set
		{
			this.registrationField = value;
		}
	}
	[XmlElement("registration")]
	public System.Xml.XmlCDataSection registration_cdata
    {
        get
        {
			return new System.Xml.XmlDocument().CreateCDataSection(registrationField);
        }
        set
        {
			registrationField = value.Value;
        }
    }
	
	[XmlIgnore]
	public int registration_interval
	{
		get
		{
			return this.registration_intervalField;
		}
		set
		{
			this.registration_intervalField = value;
		}
	}

	[XmlElement("registration_interval")]
	public System.Xml.XmlCDataSection registration_interval_cdata
	{
		get
		{
			return new System.Xml.XmlDocument().CreateCDataSection(registration_intervalField.ToString());
		}
		set
		{
			int.TryParse(value.Value, out registration_intervalField);
		}
	}

	[XmlIgnore]
	public string domain
	{
		get
		{
			return this.domainField;
		}
		set
		{
			this.domainField = value;
		}
	}
	[XmlElement("domain")]
	public System.Xml.XmlCDataSection domain_cdata
	{
		get
		{
			return new System.Xml.XmlDocument().CreateCDataSection(domainField);
		}
		set
		{
			domainField = value.Value;
		}
	}
	
	[XmlIgnore]
	public int domain_port
	{
		get
		{
			return this.domain_portField;
		}
		set
		{
			this.domain_portField = value;
		}
	}

	[XmlElement("domain_port")]
	public System.Xml.XmlCDataSection domain_port_cdata
	{
		get
		{
			return new System.Xml.XmlDocument().CreateCDataSection(domain_portField.ToString());
		}
		set
		{
			int.TryParse(value.Value, out domain_portField);
		}
	}
	
	/// <remarks/>
	[XmlIgnore]
	public string proxy
	{
		get
		{
			return this.proxyField;
		}
		set
		{
			this.proxyField = value;
		}
	}

	[XmlElement("proxy")]
	public System.Xml.XmlCDataSection proxyField_cdata
	{
		get
		{
			return new System.Xml.XmlDocument().CreateCDataSection(this.proxyField);
		}
		set
		{
			this.proxyField = value.Value;
		}
	}

	/// <remarks/>
	[XmlIgnore]
	public int proxy_port
	{
		get
		{
			return this.proxy_portField;
		}
		set
		{
			this.proxy_portField = value;
		}
	}

	[XmlElement("proxy_port")]
	public System.Xml.XmlCDataSection proxy_port_cdata
	{
		get
		{
			return new System.Xml.XmlDocument().CreateCDataSection(this.proxy_portField.ToString());
		}
		set
		{
			int.TryParse(value.Value, out this.proxy_portField);
		}
	}

	/// <remarks/>
	[XmlIgnore]
	public int local_port
	{
		get
		{
			return this.local_portField;
		}
		set
		{
			this.local_portField = value;
		}
	}

	[XmlElement("local_port")]
	public System.Xml.XmlCDataSection local_port_cdata
	{
		get
		{
			return new System.Xml.XmlDocument().CreateCDataSection(this.local_portField.ToString());
		}
		set
		{
			int.TryParse(value.Value, out this.local_portField);
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string user_name
	{
		get
		{
			return this.user_nameField;
		}
		set
		{
			this.user_nameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string login
	{
		get
		{
			return this.loginField;
		}
		set
		{
			this.loginField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string password
	{
		get
		{
			return this.passwordField;
		}
		set
		{
			this.passwordField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string keepalive
	{
		get
		{
			return this.keepaliveField;
		}
		set
		{
			this.keepaliveField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string keepalive_interval
	{
		get
		{
			return this.keepalive_intervalField;
		}
		set
		{
			this.keepalive_intervalField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string dtmf_type
	{
		get
		{
			return this.dtmf_typeField;
		}
		set
		{
			this.dtmf_typeField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string codec1
	{
		get
		{
			return this.codec1Field;
		}
		set
		{
			this.codec1Field = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string codec2
	{
		get
		{
			return this.codec2Field;
		}
		set
		{
			this.codec2Field = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string codec3
	{
		get
		{
			return this.codec3Field;
		}
		set
		{
			this.codec3Field = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string codec4
	{
		get
		{
			return this.codec4Field;
		}
		set
		{
			this.codec4Field = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string cid_where
	{
		get
		{
			return this.cid_whereField;
		}
		set
		{
			this.cid_whereField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string rejection_code
	{
		get
		{
			return this.rejection_codeField;
		}
		set
		{
			this.rejection_codeField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class configGsm
{

	private string record_inField;

	private string record_outField;

	private string record_sipField;

	private string cid_fromField;

	private string jitter_maxField;

	private string jitter_halfField;

	private string jitter_fill_if_emptyField;

	private string audio_rxgainField;

	private string audio_txgainField;

	private string only_2GField;

	private string dtmf_row_0Field;

	private string dtmf_row_1Field;

	private string dtmf_row_2Field;

	private string dtmf_row_3Field;

	private string dtmf_col_0Field;

	private string dtmf_col_1Field;

	private string dtmf_col_2Field;

	private string dtmf_col_3Field;

	private string atd_response_timeoutField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string record_in
	{
		get
		{
			return this.record_inField;
		}
		set
		{
			this.record_inField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string record_out
	{
		get
		{
			return this.record_outField;
		}
		set
		{
			this.record_outField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string record_sip
	{
		get
		{
			return this.record_sipField;
		}
		set
		{
			this.record_sipField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string cid_from
	{
		get
		{
			return this.cid_fromField;
		}
		set
		{
			this.cid_fromField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string jitter_max
	{
		get
		{
			return this.jitter_maxField;
		}
		set
		{
			this.jitter_maxField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string jitter_half
	{
		get
		{
			return this.jitter_halfField;
		}
		set
		{
			this.jitter_halfField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string jitter_fill_if_empty
	{
		get
		{
			return this.jitter_fill_if_emptyField;
		}
		set
		{
			this.jitter_fill_if_emptyField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string audio_rxgain
	{
		get
		{
			return this.audio_rxgainField;
		}
		set
		{
			this.audio_rxgainField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string audio_txgain
	{
		get
		{
			return this.audio_txgainField;
		}
		set
		{
			this.audio_txgainField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string only_2G
	{
		get
		{
			return this.only_2GField;
		}
		set
		{
			this.only_2GField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string dtmf_row_0
	{
		get
		{
			return this.dtmf_row_0Field;
		}
		set
		{
			this.dtmf_row_0Field = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string dtmf_row_1
	{
		get
		{
			return this.dtmf_row_1Field;
		}
		set
		{
			this.dtmf_row_1Field = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string dtmf_row_2
	{
		get
		{
			return this.dtmf_row_2Field;
		}
		set
		{
			this.dtmf_row_2Field = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string dtmf_row_3
	{
		get
		{
			return this.dtmf_row_3Field;
		}
		set
		{
			this.dtmf_row_3Field = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string dtmf_col_0
	{
		get
		{
			return this.dtmf_col_0Field;
		}
		set
		{
			this.dtmf_col_0Field = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string dtmf_col_1
	{
		get
		{
			return this.dtmf_col_1Field;
		}
		set
		{
			this.dtmf_col_1Field = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string dtmf_col_2
	{
		get
		{
			return this.dtmf_col_2Field;
		}
		set
		{
			this.dtmf_col_2Field = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string dtmf_col_3
	{
		get
		{
			return this.dtmf_col_3Field;
		}
		set
		{
			this.dtmf_col_3Field = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string atd_response_timeout
	{
		get
		{
			return this.atd_response_timeoutField;
		}
		set
		{
			this.atd_response_timeoutField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class configGate
{

	private string work_modeField;

	private string sip_default_numberField;

	private string gsm_default_numberField;

	private string gsm_dialing_timeoutField;

	private string sip_gsm_commutateField;

	private string send_progressField;

	private string dial_wait_timeoutField;

	private string dial_end_symbolField;

	private string dial_end_timeoutField;

	private string check_sip_prefixField;

	private string sip2gsm_only_default_numberField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string work_mode
	{
		get
		{
			return this.work_modeField;
		}
		set
		{
			this.work_modeField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string sip_default_number
	{
		get
		{
			return this.sip_default_numberField;
		}
		set
		{
			this.sip_default_numberField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string gsm_default_number
	{
		get
		{
			return this.gsm_default_numberField;
		}
		set
		{
			this.gsm_default_numberField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string gsm_dialing_timeout
	{
		get
		{
			return this.gsm_dialing_timeoutField;
		}
		set
		{
			this.gsm_dialing_timeoutField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string sip_gsm_commutate
	{
		get
		{
			return this.sip_gsm_commutateField;
		}
		set
		{
			this.sip_gsm_commutateField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string send_progress
	{
		get
		{
			return this.send_progressField;
		}
		set
		{
			this.send_progressField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string dial_wait_timeout
	{
		get
		{
			return this.dial_wait_timeoutField;
		}
		set
		{
			this.dial_wait_timeoutField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string dial_end_symbol
	{
		get
		{
			return this.dial_end_symbolField;
		}
		set
		{
			this.dial_end_symbolField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string dial_end_timeout
	{
		get
		{
			return this.dial_end_timeoutField;
		}
		set
		{
			this.dial_end_timeoutField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string check_sip_prefix
	{
		get
		{
			return this.check_sip_prefixField;
		}
		set
		{
			this.check_sip_prefixField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string sip2gsm_only_default_number
	{
		get
		{
			return this.sip2gsm_only_default_numberField;
		}
		set
		{
			this.sip2gsm_only_default_numberField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class NewDataSet
{

	private config[] itemsField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("config")]
	public config[] Items
	{
		get
		{
			return this.itemsField;
		}
		set
		{
			this.itemsField = value;
		}
	}
}
