//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalanceChecker {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Na rahunku: ([0-9,\.]+) grn\.</string>
  <string>([0-9,\.]+) UAH,</string>
  <string>Na Vashomu rahunku ([0-9,\.]+) grn</string>
  <string>Balans ([0-9,\.]+)hrn</string>
  <string>Balans ([0-9,\.]+) hrn</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AmountRegExList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AmountRegExList"]));
            }
            set {
                this["AmountRegExList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>*111#</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CheckBalanceNumberList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CheckBalanceNumberList"]));
            }
            set {
                this["CheckBalanceNumberList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int USSDSendTimeout {
            get {
                return ((int)(this["USSDSendTimeout"]));
            }
            set {
                this["USSDSendTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int SerialPortTimeout {
            get {
                return ((int)(this["SerialPortTimeout"]));
            }
            set {
                this["SerialPortTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\log.txt")]
        public string LogFilePath {
            get {
                return ((string)(this["LogFilePath"]));
            }
            set {
                this["LogFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ServiceStopTime {
            get {
                return ((int)(this["ServiceStopTime"]));
            }
            set {
                this["ServiceStopTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SipGsmService")]
        public string SipGsmServiceName {
            get {
                return ((string)(this["SipGsmServiceName"]));
            }
            set {
                this["SipGsmServiceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableLogging {
            get {
                return ((bool)(this["EnableLogging"]));
            }
            set {
                this["EnableLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CheckerInterval {
            get {
                return ((int)(this["CheckerInterval"]));
            }
            set {
                this["CheckerInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8182")]
        public int HTTPPort {
            get {
                return ((int)(this["HTTPPort"]));
            }
            set {
                this["HTTPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseTimer {
            get {
                return ((bool)(this["UseTimer"]));
            }
            set {
                this["UseTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseHTTP {
            get {
                return ((bool)(this["UseHTTP"]));
            }
            set {
                this["UseHTTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Balance Checker HTTP Server")]
        public string FirewallRuleName {
            get {
                return ((string)(this["FirewallRuleName"]));
            }
            set {
                this["FirewallRuleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirewallRuleDescription {
            get {
                return ((string)(this["FirewallRuleDescription"]));
            }
            set {
                this["FirewallRuleDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<html>\r\n<head>\r\n<meta charset=\"utf-8\">\r\n<title>Status</title>\r\n</head>\r\n<body bgc" +
            "olor = {0}>\r\n <h2 align=\"center\">{1}</h2>\r\n</body>\r\n</html>")]
        public string SipGsmStatusHtml {
            get {
                return ((string)(this["SipGsmStatusHtml"]));
            }
            set {
                this["SipGsmStatusHtml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int WaitForStatusTimeout {
            get {
                return ((int)(this["WaitForStatusTimeout"]));
            }
            set {
                this["WaitForStatusTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-01-05")]
        public global::System.DateTime LastCheckBalanceDate {
            get {
                return ((global::System.DateTime)(this["LastCheckBalanceDate"]));
            }
            set {
                this["LastCheckBalanceDate"] = value;
            }
        }
    }
}
